# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          image: node:14.7
          script:
            - echo "Your build and test goes here..."
            - yarn
            - yarn tsc
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        trigger: 'manual'
        script:
          - echo "Starting deployment to staging server"
          - pipe: atlassian/ssh-run:0.3.1
            variables:
              SSH_USER: 'jazy'
              SERVER: '159.65.156.184'
              MODE: 'script'
              COMMAND: 'deploy.sh'

    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."

